Dynamic:
  - PRODUCT:
    - CONCAT:
      - CompressFramwork.Path: data/DLR-internal.vtu # data/DLR-internal.vtu  data/tetBox_5000.vtk data/tetBox_0.vtk

    - CONCAT:
      - CompressFramwork.Ratio: 64

    - CONCAT:
      - CompressFramwork.Train.batch_size: 524288
        CompressFramwork.Train.epochs: 12000
        CompressFramwork.Eval.batch_size: 524288
        CompressFramwork.Eval.epochs: 500

#    - CONCAT:
#      - CompressFramwork:
#          VTK:
#            PointOrCell: 'point'          # point cell 一次只能选一种，因为这两个的输入不同
#            attribute: [ 'p' ]      # [nuTilda]
#
    - CONCAT:
      - CompressFramwork:
          Path: data/pitzDaily_78_tetra.vtk
          Train.epochs: 12000
          VTK:
            PointOrCell: 'cell'          # point cell 一次只能选一种，因为这两个的输入不同
            attribute: [ 'epsilon' ]
          Ratio: 64
          Network:
            max_level: 2
            allocation_scheme: num
            act: Sine  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
            layer: 6
        Log.project_name: pitzDaily_78_tetra_cell_epsilon
      - CompressFramwork:
          Path: data/motorBike_500_tetra.vtk
          VTK:
            PointOrCell: 'cell'          # point cell 一次只能选一种，因为这两个的输入不同
            attribute: [ 'omega' ]
          Ratio: 64
          Network:
            max_level: 2
            allocation_scheme: num
            act: Sine  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
            layer: 6
        Log.project_name: motorBike_500_tetra_cell_omega
      - CompressFramwork:
          Path: data/cylinderCrossFlow3D_16000_tetra.vtk
          VTK:
            PointOrCell: 'cell'          # point cell 一次只能选一种，因为这两个的输入不同
            attribute: [ 'p' ]
          Ratio: 64
          Network:
            max_level: 2
            allocation_scheme: num
            act: Sine  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
            layer: 6
        Log.project_name: cylinderCrossFlow3D_16000_tetra_cell_p
      - CompressFramwork:
          Path: data/res_1d5.org_1_20000_tetra.vtk
          VTK:
            PointOrCell: 'point'          # point cell 一次只能选一种，因为这两个的输入不同
            attribute: [ '_Wall' ]
          Ratio: 64
          Network:
            max_level: 2
            allocation_scheme: num
            act: Sine  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
            layer: 6
        Log.project_name: res_1d5.org_1_20000_tetra_point_Wall
      - CompressFramwork:
          Path: data/tetBox_5000_tetra.vtk
          Train.epochs: 12000
          VTK:
            PointOrCell: 'cell'          # point cell 一次只能选一种，因为这两个的输入不同
            attribute: [ 'nuTilda' ]
          Ratio: 64
          Network:
            max_level: 2
            allocation_scheme: num
            act: Sine  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
            layer: 6
        Log.project_name: tetBox_5000_tetra_cell_nuTilda


Static:
  Reproduc: 
    seed: 42
    benchmark: false
    deterministic: true
  CompressFramwork:
    Path: data/test.tif
    Ratio: 64
    Train:
      batch_size: 262144
      epochs: 10000
      device: cuda
      optimizer: 
        type: Adamax
        lr: 1e-3
      lr_scheduler:
        name: MultiStepLR   # none  MultiStepLR
        milestones: [20000,50000]
        gamma: 0.2
      weight: [2001,65535,0.01]
    Eval:
      batch_size: 262144
      epochs: 1000
      device: cuda
    Preprocess:
      normal_min: 0
      normal_max: 1
    Network:
      input: 3
      output: 1          # 废弃
      w0: 30
    VTK:
      PointOrCell: 'point'          # point cell 一次只能选一种，因为这两个的输入不同
      attribute: [ 'p' ]      # [nuTilda]

  Log: 
    project_name: default
    stdlog: false
    tensorboard: true