Dynamic:
  - PRODUCT:
    - CONCAT:
      - CompressFramwork.Path:  data/tetBox_5000.vtk # data/DLR-internal.vtu
        
    - CONCAT:
      - CompressFramwork.Ratio: 64

    - CONCAT:
      - CompressFramwork.Train.batch_size: 524288
        CompressFramwork.Train.epochs: 30000
        CompressFramwork.Eval.batch_size: 524288   # 废弃
        CompressFramwork.Eval.epochs: 1000

    - CONCAT:
#      - CompressFramwork:
#          Network:
#            max_level: 2
#            allocation_scheme: num
#            act: LeakyReLU0.005  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
#            layer: 3
#        Log.project_name: MutliTask0
#      - CompressFramwork:
#          Network:
#            max_level: 2
#            allocation_scheme: num_var
#            act: LeakyReLU0.01  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
#            layer: 5
#        Log.project_name: MutliTask1
#      - CompressFramwork:
#          Network:
#            max_level: 2
#            allocation_scheme: num_var
#            act: LeakyReLU0.01  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
#            layer: 4
#        Log.project_name: MutliTask2
      - CompressFramwork:
          Network:
            max_level: 2
            allocation_scheme: num_var
            act: LeakyReLU0.01  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
            layer: 3
        Log.project_name: MutliTask3

Static:
  Reproduc: 
    seed: 42
    benchmark: false
    deterministic: true
  CompressFramwork:
    Path: data/test.tif
    Ratio: 64
    Train:
      batch_size: 262144
      epochs: 10000
      device: cuda
      optimizer: 
        type: Adamax
        lr: 1e-3
      lr_scheduler:
        name: MultiStepLR
        milestones: [20000,50000]
        gamma: 0.2
      weight: [2001,65535,0.01]    # TODO 损失函数的权重，这个一般应该如何设置，也许可以通过getscale.py来得到？
    Eval:
      batch_size: 262144   # 废弃
      epochs: 1000
      device: cuda
    Preprocess:
      normal_min: 0
      normal_max: 1
    Network:
      input: 3
      output: 1          # 废弃
      w0: 30
    VTK:
      PointOrCell: 'point'          # point cell 一次只能选一种，因为这两个的输入不同
      attribute: [ 'p' ]      # [nuTilda]

  Log: 
    project_name: default
    stdlog: false
    tensorboard: true