Reproduc: 
  seed: 42
  benchmark: false
  deterministic: true
CompressFramwork:
  Path: data/tetBox_0.vtk
  Ratio: 64
  Train:
    batch_size: 524288  # 524288 # 262144
    epochs: 30000
    device: cuda
    optimizer: 
      type: Adamax
      lr: 1e-3
    lr_scheduler:
      name: MultiStepLR
      milestones: [20000,50000]
      gamma: 0.2
    weight: [-10,0,0.00001]
  Eval:
    batch_size: 524288  # 262144
    epochs: 1000
    device: cuda
  Preprocess:
    normal_min: 0
    normal_max: 100
  Network:
    input: 3
    output: 1      # 废弃
    #level_info: [[0.8, 3, ReLU, num],[0.8, 3, ReLU, num]]  # [parameter ratio, layer, act, allocate]
    max_level: 3
    allocation_scheme: num
    act: ReLU  # Sine, ReLU, LeakyReLU, Sigmoid, Tanh
    layer: 3
    w0: 30
  VTK:
    PointOrCell: 'point'          # 一次只能选一种，因为这两个的输入不同
    attribute: [point.nuTilda]

Log: 
  project_name: default
  stdlog: false
  tensorboard: true