Reproduc: 
  seed: 42
  benchmark: false
  deterministic: true
CompressFramwork:
  Path: data/DLR-internal.vtu
  Ratio: 64
  Train:
    batch_size: 524288  # 524288 # 262144
    epochs: 30000
    device: cuda
    optimizer: 
      type: Adamax
      lr: 1e-3
    lr_scheduler:
      name: MultiStepLR
      milestones: [20000,50000]
      gamma: 0.2
    weight: [-10,0,0.00001]
  Eval:
    batch_size: 524288  # 262144
    epochs: 1000
    device: cuda
  Preprocess:
    normal_min: 0
    normal_max: 1
  Network:
    input: 3
    output: 1      # 废弃
    max_level: 1
    allocation_scheme: num
    act: Sine  # Sine, ReLU, LeakyReLU0.01, Sigmoid, Tanh
    layer: 7
    w0: 30
  VTK:
    PointOrCell: 'point'          # point cell 一次只能选一种，因为这两个的输入不同(?
    attribute: []      # [nuTilda]

Log: 
  project_name: default
  stdlog: false
  tensorboard: true